export const BLOCK = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  SAND: 4,
  WATER: 5,
  OAK_LOG: 6,
  LEAVES: 7,
  COBBLESTONE: 8,
  PLANKS: 9,
  GLASS: 10,
  COAL_ORE: 11,
  IRON_ORE: 12,
  BEDROCK: 13,
  CRAFTING_TABLE: 14,
};

const defs = {
  [BLOCK.AIR]: {
    id: BLOCK.AIR,
    name: "Air",
    solid: false,
    mineable: false,
    placeable: false,
    renderLayer: "none",
    breakTime: 0,
    preferredTool: null,
    harvestLevel: 0,
    requiresTool: false,
    textures: {},
    tint: 0xffffff,
  },
  [BLOCK.GRASS]: {
    id: BLOCK.GRASS,
    name: "Grass Block",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 0.5,
    preferredTool: "shovel",
    harvestLevel: 0,
    requiresTool: false,
    textures: { top: "grassTop", side: "grassSide", bottom: "dirt" },
    tint: 0xffffff,
  },
  [BLOCK.DIRT]: {
    id: BLOCK.DIRT,
    name: "Dirt",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 0.45,
    preferredTool: "shovel",
    harvestLevel: 0,
    requiresTool: false,
    textures: { all: "dirt" },
    tint: 0xffffff,
  },
  [BLOCK.STONE]: {
    id: BLOCK.STONE,
    name: "Stone",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 1.5,
    preferredTool: "pickaxe",
    harvestLevel: 0,
    requiresTool: true,
    textures: { all: "stone" },
    tint: 0xffffff,
  },
  [BLOCK.SAND]: {
    id: BLOCK.SAND,
    name: "Sand",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 0.45,
    preferredTool: "shovel",
    harvestLevel: 0,
    requiresTool: false,
    textures: { all: "sand" },
    tint: 0xffffff,
  },
  [BLOCK.WATER]: {
    id: BLOCK.WATER,
    name: "Water",
    solid: false,
    mineable: false,
    placeable: false,
    renderLayer: "transparent",
    breakTime: 0,
    preferredTool: null,
    harvestLevel: 0,
    requiresTool: false,
    textures: { all: "water" },
    tint: 0x9cc8ff,
  },
  [BLOCK.OAK_LOG]: {
    id: BLOCK.OAK_LOG,
    name: "Oak Log",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 2,
    preferredTool: "axe",
    harvestLevel: 0,
    requiresTool: false,
    textures: { top: "logTop", bottom: "logTop", side: "logSide" },
    tint: 0xffffff,
  },
  [BLOCK.LEAVES]: {
    id: BLOCK.LEAVES,
    name: "Leaves",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "cutout",
    breakTime: 0.3,
    preferredTool: "axe",
    harvestLevel: 0,
    requiresTool: false,
    textures: { all: "leaves" },
    tint: 0xc9ffd3,
  },
  [BLOCK.COBBLESTONE]: {
    id: BLOCK.COBBLESTONE,
    name: "Cobblestone",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 2,
    preferredTool: "pickaxe",
    harvestLevel: 0,
    requiresTool: true,
    textures: { all: "cobble" },
    tint: 0xffffff,
  },
  [BLOCK.PLANKS]: {
    id: BLOCK.PLANKS,
    name: "Oak Planks",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 1.5,
    preferredTool: "axe",
    harvestLevel: 0,
    requiresTool: false,
    textures: { all: "planks" },
    tint: 0xffffff,
  },
  [BLOCK.GLASS]: {
    id: BLOCK.GLASS,
    name: "Glass",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "transparent",
    breakTime: 0.45,
    preferredTool: null,
    harvestLevel: 0,
    requiresTool: false,
    textures: { all: "glass" },
    tint: 0xffffff,
  },
  [BLOCK.COAL_ORE]: {
    id: BLOCK.COAL_ORE,
    name: "Coal Ore",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 3,
    preferredTool: "pickaxe",
    harvestLevel: 0,
    requiresTool: true,
    textures: { all: "coalOre" },
    tint: 0xffffff,
  },
  [BLOCK.IRON_ORE]: {
    id: BLOCK.IRON_ORE,
    name: "Iron Ore",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 3.2,
    preferredTool: "pickaxe",
    harvestLevel: 1,
    requiresTool: true,
    textures: { all: "ironOre" },
    tint: 0xffffff,
  },
  [BLOCK.BEDROCK]: {
    id: BLOCK.BEDROCK,
    name: "Bedrock",
    solid: true,
    mineable: false,
    placeable: false,
    renderLayer: "opaque",
    breakTime: Number.POSITIVE_INFINITY,
    preferredTool: null,
    harvestLevel: 99,
    requiresTool: true,
    textures: { all: "bedrock" },
    tint: 0xffffff,
  },
  [BLOCK.CRAFTING_TABLE]: {
    id: BLOCK.CRAFTING_TABLE,
    name: "Crafting Table",
    solid: true,
    mineable: true,
    placeable: true,
    renderLayer: "opaque",
    breakTime: 2.2,
    preferredTool: "axe",
    harvestLevel: 0,
    requiresTool: false,
    textures: { top: "craftingTop", bottom: "planks", side: "craftingSide", front: "craftingFront", back: "craftingSide", left: "craftingSide", right: "craftingFront" },
    tint: 0xffffff,
  },
};

export const BLOCK_TYPES = defs;

export function getBlockDefinition(id) {
  return defs[id] ?? defs[BLOCK.AIR];
}

export function getFaceTexture(blockId, faceName) {
  const textures = getBlockDefinition(blockId).textures;
  return textures[faceName] ?? textures.side ?? textures.top ?? textures.all;
}

export function isSolid(id) {
  return getBlockDefinition(id).solid;
}
